version: "3.7"
services:

  # nginx:
  #   image: nginx:1.21.1
  #   container_name: nginx
  #   depends_on:
  #     - app
  #   volumes:
  #     - ./nginx/conf.d:/etc/nginx/conf.d
  #     - ./nginx/ssl:/etc/nginx/ssl
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - 80:80
  #     - 443:443
  #   networks:
  #     - api_network

  # app:
  #   image: golang:1.16.5
  #   container_name: app
  #   depends_on:
  #     - postgres
  #   environment:
  #     - db_host=postgres
  #     - csrftoken_only_https=false
  #   ports:
  #     - 8080:8080/tcp
  #   volumes:
  #     - ./app:/go/src/app
  #     - ./keypair:/tmp/localhost/docker-compose/keypair
  #   working_dir : /go/src/app
  #   command: sh -c "go run main.go"
  #   networks:
  #     - api_network

  mysql:
    image: mariadb:10.7.3
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_side_project
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - api_network

networks:
  api_network:
    name: api_network