name: coverage

on: 
  push:
    branches:
      - master
    paths:
      - '.github/workflows/coverage.yml'
      - 'app/**'

jobs:
  my-job-coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.16'

      - name: Check out code
        uses: actions/checkout@v3

      - name: Produce Coverage report
        run: |
          make key
          go test ./app/handler/ -coverprofile=coverage.out
          ls -al

      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: ./coverage.out